default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: aleksey

development:
  <<: *default
  database: myapp_development
  password: '1qaz2wsx'

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
